[package]
name = "arangoq"
version = "0.2.0"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
arangoq_derive = { path = "./arangoq_derive" }
futures = "0.1.0"
log = "0.4.8"
maplit = "1.0.2"
reqwest = { version = "0.9.21" }
serde = { version = "1.0.102", features = ["derive"] }
serde_derive = "1.0.102"
serde_json = "1.0.41"

[features]
# no features by default
default = []

[dev-dependencies]
actix = "0.8.3"
actix-rt = "0.2.5"
actix-web = { version= "1.0.8" }
env_logger = "0.7.1"
mockito = "0.21.0"

