[package]
name = "arangoq"
version = "0.2.1-alpha.0"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
arangoq_derive = { path = "./arangoq_derive" }
futures = "0.1"
log = "0.4"
maplit = "1.0"
reqwest = { version = "0.9" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[features]
# no features by default
default = []

[dev-dependencies]
actix = "0.8.3"
actix-rt = "0.2.5"
actix-web = { version= "1.0.8" }
env_logger = "0.7.1"
mockito = "0.21.0"
proptest = "0.9.4"
proptest-derive = "0.1.2"
lazy_static = "1.4.0"
