# image: gitlab/dind
#image: docker:git
image: rust:1.39

# dind requires runners.docker volumes to contain "/certs/client", privileged = true and wait_for_services_timeout = 120 at least
#services:
#  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: normal
  CARGO_HOME: /tmp/.cargo
  CARGO_TARGET_DIR: /tmp/.cargo/target

stages:
  - test

# add /tmp/.cargo to runners.docker.volumes in runner config to share compiled deps between runs
test_and_clippy:
  stage: test
  tags: [rust]
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - CARGO_TARGET_DIR=/tmp/.cargo/target CARGO_HOME=/tmp/.cargo cargo fmt
    - CARGO_TARGET_DIR=/tmp/.cargo/target CARGO_HOME=/tmp/.cargo CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture
    - CARGO_TARGET_DIR=/tmp/.cargo/target CARGO_HOME=/tmp/.cargo CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo clippy --tests
