[package]
name = "arangoq_derive"
version = "0.1.1-alpha.1"
authors = ["bsoptei <bsoptei@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4.30"
quote = "0.6.13"

[dependencies.syn]
version = "0.15.42"
features = ["full"]

[lib]
proc-macro = true

